version: '2'
services:
  mongo:
    image: "mongo:3"

  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog:
    image: graylog2/server:2.1.0-3
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://192.168.99.100:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"

  db:
    image: postgres

  rabbit:
    #image: rabbitmq
    image: rabbitmq:3-management
    ports:
      #- "5672:5672"
      - "9090:15672"

  web:
    build: ./web_1/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./web_1/:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbit
    links:
      - rabbit

  web2:
    build: ./web_2/
    #volumes:
      #- ./web_2/:.
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
    links:
      - rabbit